{
 "title": "Clash dashboard",
 "description": "Clash exporter example dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, source)"
    }
   },
   {
    "name": "policy",
    "label": "policy",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, policy)"
    }
   },
   {
    "name": "type",
    "label": "type",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total, type)"
    }
   },
   {
    "name": "source_name",
    "label": "来源主机",
    "query": {
     "query": "label_values(clash_network_traffic_bytes_total,source_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "版本",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max (clash_info) by (version, premium)"
    }
   ]
  },
  {
   "title": "总下载量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(clash_download_bytes_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总上传量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(clash_upload_bytes_total[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS 请求数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(clash_tracing_dns_request_duration_milliseconds_count[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(clash_active_connections[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时网速",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"download\"}[$__range]))",
     "legendFormat": "download"
    },
    {
     "expr": "sum(rate(clash_network_traffic_bytes_total{type=\"upload\"}[$__range]))",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "客户端总流量",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (source,source_name) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "代理总流量",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (policy) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\", type=~\"$type\"}[$__range]))",
     "legendFormat": "来源"
    }
   ]
  },
  {
   "title": "目的地总流量",
   "type": "table",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by (destination) (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[$__range]))))",
     "legendFormat": "来源"
    }
   ]
  },
  { "title": "Traffic Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "策略流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h])) by (policy)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h])) by (policy)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h]))  by (policy)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d])) by (policy)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m])) by (policy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户端流量统计",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1h])) by (source)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[3h])) by (source)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[6h])) by (source)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[1d])) by (source)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  (increase(clash_network_traffic_bytes_total{source=~\"$source\", policy=~\"$policy\",type=~\"$type\"}[5m])) by (source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracing Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rule Match Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(clash_tracing_rule_match_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_rule_match_duration_milliseconds_count{}[1m]))",
       "legendFormat": "AVG"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_rule_match_duration_milliseconds_bucket{}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Proxy Dial Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(clash_tracing_proxy_dial_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_proxy_dial_duration_milliseconds_count{}[1m]))",
       "legendFormat": "AVG"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_proxy_dial_duration_milliseconds_bucket{}[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "DNS Request Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(clash_tracing_dns_request_duration_milliseconds_sum{}[1m])) / sum(irate(clash_tracing_dns_request_duration_milliseconds_count{}[1m]))",
       "legendFormat": "AVG"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(clash_tracing_dns_request_duration_milliseconds_bucket[1m])) by (le))",
       "legendFormat": "P99"
      }
     ]
    }
   ]
  }
 ]
}